rvm:
  - 2.1.3
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx-2
gemfile:
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
matrix:
  exclude:
    - { rvm: jruby, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: rbx-2, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 1.9.3, gemfile: test/gemfiles/Gemfile.rails-4.1.x }
    - { rvm: 2.0.0, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 2.1.3, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  fast_finish: true
script: "bundle exec rake submodules test"
